config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # devise_for :users
  get 'sessions/new'
  root 'pages#home'
  # resources :pages
  # resources :pages, only: [:index]
  get  '/about',  to: 'pages#about'
  get  '/signup',  to: 'users#new' #signup=新規
  get    '/login',   to: 'sessions#new'#ログインのフォーム
  post   '/login',   to: 'sessions#create'#postリクエストで実際にログイン
  delete '/logout',  to: 'sessions#destroy'#ログアウト
  resources :users
  resources :account_activations, only: [:edit]
  
  #/posts/1/comment/とかになる。
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/smooth' => 'users#smooth', as: 'smooth_edit'



#_follow_formのrender follow,unfollow用
  resources :relationships,       only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  

  get '/search' => 'search#search'

  #tag
  get 'posts/hashtag/:name', to:'posts#hashtags'
  # resources :tags, only: [:index, :show]


# ゲストログイン
#resources :smooth_login_session, only: :create
resources :testsessions, only: :create
  #memberで、users/1/followingが実現できる。https://pikawaka.com/rails/resources#ネストの定義の仕方
  resources :users do
    member do 
      get :following, :followers
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post, optional: true
    belongs_to :user
    validates :content,  presence: true, length: { maximum: 1000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
       @post = Post.find(params[:post_id])
       #build=new。慣習的にbuildを使っている。
       @comment = @post.comments.build(comment_params)
       @comment.user_id = current_user.id
       if @comment.save
        flash[:success] = "コメントしました！"
        redirect_to request.referrer || root_url
       end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:success] = "コメントを削除しました！"
      redirect_to request.referrer || root_url
    end

      private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%#ネストされているルーティングの場合は、親子それぞれのモデルを記述する。 %>
  <div>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "コメントをする", class: 'btn btn-primary mt-4', data: { disable_with: "コメントしています..." } %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to "#{comment.user.name}", user_path(comment.user.id) %>さんのコメント</p>
    <p><%= comment.content %></p>
     <% if comment.user == current_user %>　　　　　　　　　　<%##post/1/comment32とかのため。 %>
      <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true %></p>
    <% end %>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')