config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # devise_for :users
  get 'sessions/new'
  root 'pages#home'
  # resources :pages
  # resources :pages, only: [:index]
  get  '/about',  to: 'pages#about'
  get  '/signup',  to: 'users#new' #signup=新規
  get    '/login',   to: 'sessions#new'#ログインのフォーム
  post   '/login',   to: 'sessions#create'#postリクエストで実際にログイン
  delete '/logout',  to: 'sessions#destroy'#ログアウト
  resources :users
  resources :account_activations, only: [:edit]
  
  #/posts/1/comment/とかになる。
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/smooth' => 'users#smooth', as: 'smooth_edit'



#_follow_formのrender follow,unfollow用
  resources :relationships,       only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  

  get '/search' => 'search#search'

  #tag
  get 'posts/hashtag/:name', to:'posts#hashtags'
  # resources :tags, only: [:index, :show]


# ゲストログイン
#resources :smooth_login_session, only: :create
resources :testsessions, only: :create
  #memberで、users/1/followingが実現できる。https://pikawaka.com/rails/resources#ネストの定義の仕方
  resources :users do
    member do 
      get :following, :followers
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes
    # 自分がlikeした投稿
    has_many :liked_posts, through: :likes, source: :post
    
    #アバター
    mount_uploader :avatar, AvatarUploader
    #view数
    is_impressionable counter_cache: true
    ############following関係######################################
    has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
    has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
    has_many :following, through: :active_relationships, source: :followed#sourceの意味 → following配列の元はfollowedIdのかたまりであるという意味。
    has_many :followers, through: :passive_relationships, source: :follower
     ############following関係######################################
    default_scope -> { order(created_at: :desc) }
    attr_accessor :remember_token, :activation_token
    before_save   :downcase_email
    before_create :create_activation_digest
    #validation
    validates :name,  presence: true, length: { maximum: 100 }   
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 200 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: true
    validates :year,  presence: true, length: { maximum: 4 }#5年以上で4文字列分だから。
    validates :bio,  presence: true, length: { maximum: 300 }
     #User作成で、passwordとpassword_confirmation,authenticateが使える。DBテーブルにはないが。
     has_secure_password
     #password: パスワードが空でも、updateできるようにする。
     validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

     def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

  #sessionとtoken
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def session_token
    remember_digest || remember
  end

  # mailerのトークンとダイジェストが一致したか？
  # def authenticated?(attribute, token)
  #   digest = send("#{attribute}_digest")
  #   return false if digest.nil?
  #   BCrypt::Password.new(digest).is_password?(token)
  # end
  # #アカウントを有効化
  # def activate
  #   update_attribute(:activated,    true)
  #   update_attribute(:activated_at, Time.zone.now)
  # end
  # #アカウント有効のメールを送信する
  # def send_activation_email
  #   UserMailer.account_activation(self).deliver_now
  # end


  #全てのユーザーがfeedを持つから。(まだ完全ではない。)
  def feed
    Post.where("user_id = ?", id)#=posts
  end

  #####################followingメソッド###########################
  #<<は、配列の最後に追記するという意味。

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  #####################いいねのメソッド#########################################
  #likeテーブル内に、post_idが存在しているかどうか。
  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

    private

        def downcase_email
            self.email = email.downcase
        end
    # 有効化トークンとダイジェストを作成および代入。ユーザーが作られる前にそのトークンとダイジェストが必要だから。
     def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  # 特定のユーザーを表示する
  def show
    @user=User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @smooth_login_user = User.find_by(email: "smooth_login@example.com")
    @newer_posts = @user.posts.order(created_at: 'DESC')
  end

  # rails-ujsで実装したので、コメントアウト。
  # def smooth
  #   flash[:danger] = "ゲストユーザーは編集できません。"
  #   redirect_to request.referrer || 'users/1'
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "ベルリンなうへようこそ！さっそく右上のボタンからログインしよう！ →"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      #成功
      flash[:success]="Updateしました。"
      redirect_to @user
    else
      #失敗
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end

  def following
   @title = "Following"
   @user  = User.find(params[:id])
   @users = @user.following.paginate(page: params[:page])
   render 'show_follow'    
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :year, :bio, :avatar, :password,
                                 :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar_link.html.erb
<%= link_to @user.avatar.url, user_path(@user) %>

app/views/users/_bio.html.erb
  <div class="card bg-white mb-10">
　　<div class="card-body text-center">
    <h3 class="card-title"><i class="fas fa-globe-asia"></i> ベルリン在住歴: <strong><%= @user.year %></strong></h3>
    <h4 class="card-text mt-4"><%= @user.bio %></h4>
  　</div>
　</div>
<p class="card-text mt-4 ml-4">投稿数: <%= @user.posts.count %></p>
<p class="card-text ml-4">いいねをした数: <%= @user.likes.count %></p>

app/views/users/_edit_profile.html.erb
<% if current_user?(@user) %>

      <div class="text-center">
      <button type="button" class="btn btn-warning">
    <% if @user.email == "smooth_login@example.com" %>
    <%# link_to 'プロフィール編集' ,smooth_edit_path, class: 'text-light edit-btn' %>
    <%= link_to 'プロフィール編集' , "javascript:alert('ゲストユーザーは編集できません。')", class: 'text-light edit-btn' %>
    <% else %>
    <%= link_to 'プロフィール編集' ,edit_user_path(@user), class: 'text-light edit-btn' %>
    <% end %>
    </button>
    </div>

    <% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<%# ユーザーをフォローする際のボタン %>
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
   <%#_unfollow.html.erb %>
    <%= render 'unfollow' %>
  <% else %>
   <%#_follow.html.erb %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, local: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/_users_posts.html.erb
<div id="post" class="tab-pane active">　　
  <% if @newer_posts.exists? %>　
　    <% @newer_posts.each do |post| %>
      <%# <div class="card" style="width: 50rem;"> %>
     <%= link_to post_path(post), class: 'text-body under' do %> 
    <div class="card mt-4">
    <%= image_tag post.image.url, class: "img-fluid" %>
     <% end %><%# posts#show %>
     <div class="card-body">
     <h5 class="card-title">
     <%# avatar  %>
     <span class="small">
     <%= link_to user_path(post.user), class: 'under' do %>
     <% if post.user.avatar? %>
     <%= image_tag post.user.avatar.url, class: "rounded-circle mb-3", width: "40px", height: "40px" %>
     <% else %>
     <%= image_tag "the-main.jpg", class: "rounded-circle", width: "40px", height: "40px" %>
     <% end %>
    <% end %>
    <%# name %>
    <%= post.user.name %></span><br>
    <%# covid  %>
     記事内容: <span class="small bg-warning">
    <%= post.covid %>
    </span>
    <%# title  %>
    <h3><%= post.title %></h3> 
    <%# tag, description  %>
    <span><%= render_with_hashtags(post.content.truncate(85)) %><%= link_to '続きを読む', post_path(post) %></span> 
   </h5>   
    <p class="card-text">
        <%# likes %>
        <span>
         <div class="post-like">
        <%= render 'shared/likes', post: post %> 
        </div>
        </span>
    <%# impression %>
       <span>
       <i class="fas fa-eye"><%= post.impressions_count %></i>
      </span>
     <p>
      <%= time_ago_in_words(post.created_at) %> 前
      </p>

    <h5 class="card-title">
    <%#編集, 削除 %>
    <span>
    <% if current_user?(@user) %>
    <%= link_to edit_post_path(post) do %>
    <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to post, method: :delete, data: { confirm: "削除してよろしいですか?" } do %>
    <i class="fas fa-trash"></i>
    <% end %>
    <% end %><%# current_user %>
    <span>
    </h5>

        </p><%# card-text %>
      </div><%# card-body %>
    </div><%# card %>

  

　　 </div><%# card-text %>
      </div><%# card-body %>
     </div><%# card %>
     <% end %><%# each %>
     <% else %>
     <div class="text-canter">
     <p>まだ投稿がありません。<p>
     <%= link_to '投稿する', new_post_path %>
     </div>
     <% end %>
   </div>
   <%# paginate @user.posts %>
<%# <%= paginate @posts %> 



  

app/views/users/edit.html.erb
<% if @user.email == "smooth_login@example.com" %>
<p>ゲストユーザーは編集できません</p>
<%= link_to :back do %>
  <button>戻る</button>
<% end %>
<% else %>
<h1>プロフィールの更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

     <%= f.label :avatar, class: "mt-4" %>
  　　<%= f.file_field :avatar, class: "form-control" %>

      <%# @userで自動的にnameが入ってる。 %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
　　　　　
　　　　<%# @userで自動的にemailが入ってる。 %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :year, "ベルリン滞在、渡航歴", class: 'mt-4' %>
　　 　<%= f.select :year, ["1年", "2年", "3年", "4年", "5年以上"], class: 'form-control' %>

      <%= f.label :bio, "あなたについて何か書こう", class: 'mt-4' %> 
  　　 <%= f.text_field :bio, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary save-changes-btn" %>
    <% end %>

  </div>
</div>

 <% end %>

app/views/users/index.html.erb
<div class="text-center">
<h1>ユーザー一覧</h1>
</div>

<% @users.each do |user| %> 
  
<li class="mt-2">

 <% if user.avatar? %>
     <%= image_tag user.avatar.url, class: "rounded-circle ", width: "40px", height: "40px" %>
     <% else %>
     <%= image_tag "the-main.jpg", class: "rounded-circle", width: "40px", height: "40px" %>
     <% end %>  <%# avatar %>
  
  <%= link_to user.name, user %>

  <% if user.name == "ゲストユーザー" %>
  | <%= link_to "このユーザーは削除することができません", users_path %>
  <% elsif current_user?(user) %> 
    | <%= link_to "アカウントを削除する", user, method: :delete,
                                  data: { confirm: "アカウントを削除しますか？" } %>
  <% end %> <%# if %>
</li>

  <% end %>  <%# each %>  

app/views/users/new.html.erb
<div class="container">
<div class="row">

<div class="mx-auto" style="width: 500px;">

<% provide(:title, "Signup") %>
<div class="card mt-4">
<div class="card-body">
    
 <h1>新規ユーザー登録</h1>
<%###################これ参考にするhttps://pikawaka.com/rails/form_with#################################%>

  <%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  　　<%# Avatar %>
  　　<%= f.label :avatar, class: "mt-4" %>
  　　<%= f.file_field :avatar, class: "form-control" %>

　　　　<%#名前 %>
      <%= f.label :name, class: 'mt-4' %>
      <%= f.text_field :name, class: 'form-control' %>
  

      
　　　　<%#email %>
      <%= f.label :email, class: 'mt-4' %>
      <%= f.email_field :email, class: 'form-control' %>
    
      <%#password %>
      <%= f.label :password, class: 'mt-4' %>
      <%= f.password_field :password, class: 'form-control' %>
      
      
      <%#password確認 %>
      <%= f.label :password_confirmation, "Password確認", class: 'mt-4' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

       <%#滞在歴 %>
      <%= f.label :year, "ベルリン滞在、渡航歴", class: 'mt-4' %>
　　 　<%= f.select :year, ["1年", "2年", "3年", "4年", "5年以上"], class: 'form-control' %>
      
      <%#bio%>
      <%= f.label :bio, "あなたについて何か書こう", class: 'mt-4' %> 
  　　 <%= f.text_field :bio, class: 'form-control' %>


     　<%# 送信 %>
      <div class="text-center">
  　　 <%= f.submit "アカウント作成", class: "btn btn-primary mr-4" %>
     </div>
    　<% end %>

     









 

   

app/views/users/show.html.erb
<div class="mx-auto" style="width: 900px;">
    <div class="text-center">
     <%# avatar %>
     <% if @user.avatar? %>
     <%= image_tag @user.avatar.url, class: "rounded-circle ", width: "100px", height: "100px" %>
     <% else %>
     <%= image_tag "the-main.jpg", class: "rounded-circle", width: "100px", height: "100px" %>
     <% end %>
     <%# following/followed %>
     <%= render 'follow_form' if logged_in? %>
    <%# name %>
    <h1><%= @user.name %></h1>
    <%# プロフィール編集 %>
    <%= render 'users/edit_profile' %>
    <%# follow数, followed数 %>
    <%= render 'shared/stats' %>
    <%# ベルリン歴、bio,いいねもらった数、投稿数 %>
    <div class="text-left">
    <%= render 'users/bio' %>
    </div>
    </div><%#text-center %>
<%# 各ユーザーの投稿 %>
<main class="p-3">
<div class="tab-content">
<%= render 'users_posts' %>
<%# いいねした投稿がまだない %>
<%# render 'users_likes' %>
</div><%# tab-content %>
</main>

app/views/users/show_follow.html.erb
<div class="text-left mt-4">
  <h4><%= @user.name %>の<%= @title %>一覧</h4>
  <% if @users.any? %>   
    <%= render @users %>
    <% else %>
    まだ<%= @title %>がいません。
  <% end %>
</div>

app/views/users/smooth.html.erb
<%# リダイレクト用として使っているから、何も記載していない %>