config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # devise_for :users
  get 'sessions/new'
  root 'pages#home'
  # resources :pages
  # resources :pages, only: [:index]
  get  '/about',  to: 'pages#about'
  get  '/signup',  to: 'users#new' #signup=新規
  get    '/login',   to: 'sessions#new'#ログインのフォーム
  post   '/login',   to: 'sessions#create'#postリクエストで実際にログイン
  delete '/logout',  to: 'sessions#destroy'#ログアウト
  resources :users
  resources :account_activations, only: [:edit]
  
  #/posts/1/comment/とかになる。
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/smooth' => 'users#smooth', as: 'smooth_edit'



#_follow_formのrender follow,unfollow用
  resources :relationships,       only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  

  get '/search' => 'search#search'

  #tag
  get 'posts/hashtag/:name', to:'posts#hashtags'
  # resources :tags, only: [:index, :show]


# ゲストログイン
#resources :smooth_login_session, only: :create
resources :testsessions, only: :create
  #memberで、users/1/followingが実現できる。https://pikawaka.com/rails/resources#ネストの定義の仕方
  resources :users do
    member do 
      get :following, :followers
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      formにエラーが <%= pluralize(object.errors.count, "箇所") %>あります.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_likes.html.erb
 <%# このpostは、意味をなさない。renderで定義されて初めて実装される %>

 <% if logged_in? %>

 <% if current_user.liked_by?(post.id) %>

  <td>
  <%= link_to destroy_like_path(post), method: :DELETE, remote: true do %>
  <%# binding.pry %>
  <i class="fas fa-heart"></i>
  <% end %>
  <%= post.likes.count %>
  </td>

  <% else %>

  <td>
  <%= link_to create_like_path(post), method: :POST, remote: true do %>
  <i class="far fa-heart"></i>
  <% end %><%= post.likes.count %>
  </td>
  <% end %>


 <% end %>

<style>
.fa-heart{
  color:red; 
}
</style>

app/views/shared/_news_api.html.erb
<% if @news_output.empty? %>

  <li class="list-group-item">
 <%= link_to @news_output['articles'][0]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][0]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][0]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][0]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][0]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>
  </li>

    <li class="list-group-item">
     <%= link_to @news_output['articles'][1]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][1]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][1]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][1]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][1]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>
  </li>
    <li class="list-group-item">
     <%= link_to @news_output['articles'][2]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][2]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][2]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][2]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][2]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>

  <li class="list-group-item">
     <%= link_to @news_output['articles'][3]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][3]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][3]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][3]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][3]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>

     <li class="list-group-item">
     <%= link_to @news_output['articles'][4]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][4]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][4]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][4]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][4]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>

     <li class="list-group-item">
     <%= link_to @news_output['articles'][5]['url'], target: "_blank" do %> 
    <%# <div class="card"> %>
      <% if @news_output['articles'][5]['urlToImage'].nil? %>
      <%= image_tag "no_image.png", class: 'img-fluid'%>
      <% else %>
      <%= image_tag @news_output['articles'][5]['urlToImage'], class: "img-fluid" %>
      <% end %>
      <%# <div class="card-body"> %>
      <small><%= @news_output['articles'][5]['publishedAt'] %></small>
        <p class="card-title"><%= @news_output['articles'][5]['title'] %></p>
      <%# </div>
     </div> %>
   <% end %>



   <% else %>

<%# <li class="list-group-item">
<div class='text-center'>
   <p>you got too many requests :(</p>
<h1><i class="far fa-sad-tear"></i></h1></div>
</li> %>

<li class="list-group-item">
<%= link_to 'https://http.cat/' do %>
<%= image_tag 'https://http.cat/429', class: "img-fluid" %>
<% end %>
</li>

   <% end %>

app/views/shared/_post_form.html.erb
<h1 class="text-center mt-4">新規投稿</h1>

<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

   <%= f.label :投稿内容の時期, class: "mt-4" %>
   <%= f.select :covid, ["コロナ前", "コロナ後"], class: "form-control mt-4" %>

  <%# <%= f.label :title, class: 'mb-3' %> 
  <%= f.text_field :title, class: 'form-control form-control-lg mt-4', placeholder: "title" %>

  <div class="field">
    <%= f.text_area :content, placeholder: "あなたのベルリンでの経験をシェアしよう。タグ(#)は、前後にスペースを空けてください", class: "form-control mt-4", id: "exampleFormControlTextarea1" %>
  </div>

 <%# サムネイル %>
   <%= f.label :サムネイル, class: "mt-4" %> 
  <%= f.file_field :image, class: "form-control" %> 

<div class="text-center">
  <%= f.submit "投稿する", class: "btn btn-warning mt-4 text-white", data: { confirm: "この内容で投稿してよろしいですか？" , disable_with: "投稿しています..."} %>
</div>
<% end %>

app/views/shared/_stats.html.erb
<%# フォロー、フォロワー情報を表す %>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%# link_to current_user, current_user %>
<h1 class="mt-5"><%= current_user.name %></h1>
<%# link_to "view my profile", current_user %>
<%# <span><%# pluralize(current_user.posts.count, "post") %>

app/views/shared/_weather_api.html.erb
<%#天気ここから %>
<div class="text-center">
 <p>
  <% if @output['weather'][0]['icon'] == "01d" %>
  <%= image_tag '01d.png' %>
  <% elsif @output['weather'][0]['icon'] == "01n" %>
  <%# <span　class="mt-2">夜</span> %><%= image_tag '01n.png' %>
  <% elsif @output['weather'][0]['icon'] == "02d" %>
  <%= image_tag '02d.png' %>
  <% elsif @output['weather'][0]['icon'] == "02n" %>
  <%= image_tag '02n.png' %>
  <% elsif @output['weather'][0]['icon'] == "03d" %>
  <%= image_tag '03d.png' %>
  <% elsif @output['weather'][0]['icon'] == "03n" %>
  <%= image_tag '03n.png' %>
  <% elsif @output['weather'][0]['icon'] == "04d" %>
  <%= image_tag '04d.png' %>
  <% elsif @output['weather'][0]['icon'] == "04n" %>
  <%= image_tag '04n.png' %>
  <% elsif @output['weather'][0]['icon'] == "09d" %>
  <%= image_tag '09d.png' %>
  <% elsif @output['weather'][0]['icon'] == "09n" %>
  <%= image_tag '09n.png' %>
  <% elsif @output['weather'][0]['icon'] == "10d" %>
  <%= image_tag '10d.png' %>
  <% elsif @output['weather'][0]['icon'] == "10n" %>
  <%= image_tag '10n.png' %>
  <% elsif @output['weather'][0]['icon'] == "11d" %>
  <%= image_tag '11d.png' %>
  <% elsif @output['weather'][0]['icon'] == "11n" %>
  <%= image_tag '11n.png' %>
  <% elsif @output['weather'][0]['icon'] == "13d" %>
  <%= image_tag '13d.png' %>
  <% elsif @output['weather'][0]['icon'] == "13n" %>
  <%= image_tag '13n.png' %>
  <% elsif @output['weather'][0]['icon'] == "50d" %>
  <%= image_tag '50d.png' %>
  <% elsif @output['weather'][0]['icon'] == "50n" %>
  <%= image_tag '50n.png' %>
  <% end %><br><%= @output['weather'][0]['main'] %>, <%= @output['weather'][0]['description'] %>
  </p>
  <%# shift option 8 %>
  <p><%= @output['main']['temp'] %>°C</p>
  </div>
  
  <%# @output['timezone'] %> 
  
  <%#天気ここまで %>

app/views/shared/_weather_api_icon_only.html.erb
<%#天気ここから %>
<div class="text-center m-0 p-0">
 <p>
  <% if @output['weather'][0]['icon'] == "01d" %>
  <%= image_tag '01d.png' %>
  <% elsif @output['weather'][0]['icon'] == "01n" %>
  <%# <span　class="mt-2">夜</span> %><%= image_tag '01n.png' %>
  <% elsif @output['weather'][0]['icon'] == "02d" %>
  <%= image_tag '02d.png' %>
  <% elsif @output['weather'][0]['icon'] == "02n" %>
  <%= image_tag '02n.png' %>
  <% elsif @output['weather'][0]['icon'] == "03d" %>
  <%= image_tag '03d.png' %>
  <% elsif @output['weather'][0]['icon'] == "03n" %>
  <%= image_tag '03n.png' %>
  <% elsif @output['weather'][0]['icon'] == "04d" %>
  <%= image_tag '04d.png' %>
  <% elsif @output['weather'][0]['icon'] == "04n" %>
  <%= image_tag '04n.png' %>
  <% elsif @output['weather'][0]['icon'] == "09d" %>
  <%= image_tag '09d.png' %>
  <% elsif @output['weather'][0]['icon'] == "09n" %>
  <%= image_tag '09n.png' %>
  <% elsif @output['weather'][0]['icon'] == "10d" %>
  <%= image_tag '10d.png' %>
  <% elsif @output['weather'][0]['icon'] == "10n" %>
  <%= image_tag '10n.png' %>
  <% elsif @output['weather'][0]['icon'] == "11d" %>
  <%= image_tag '11d.png' %>
  <% elsif @output['weather'][0]['icon'] == "11n" %>
  <%= image_tag '11n.png' %>
  <% elsif @output['weather'][0]['icon'] == "13d" %>
  <%= image_tag '13d.png' %>
  <% elsif @output['weather'][0]['icon'] == "13n" %>
  <%= image_tag '13n.png' %>
  <% elsif @output['weather'][0]['icon'] == "50d" %>
  <%= image_tag '50d.png' %>
  <% elsif @output['weather'][0]['icon'] == "50n" %>
  <%= image_tag '50n.png' %>
  <% end %>
  </div>
  
  <%# @output['timezone'] %> 
  
  <%#天気ここまで %>