config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  # devise_for :users
  get 'sessions/new'
  root 'pages#home'
  # resources :pages
  # resources :pages, only: [:index]
  get  '/about',  to: 'pages#about'
  get  '/signup',  to: 'users#new' #signup=新規
  get    '/login',   to: 'sessions#new'#ログインのフォーム
  post   '/login',   to: 'sessions#create'#postリクエストで実際にログイン
  delete '/logout',  to: 'sessions#destroy'#ログアウト
  resources :users
  resources :account_activations, only: [:edit]
  
  #/posts/1/comment/とかになる。
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get '/smooth' => 'users#smooth', as: 'smooth_edit'



#_follow_formのrender follow,unfollow用
  resources :relationships,       only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  

  get '/search' => 'search#search'

  #tag
  get 'posts/hashtag/:name', to:'posts#hashtags'
  # resources :tags, only: [:index, :show]


# ゲストログイン
#resources :smooth_login_session, only: :create
resources :testsessions, only: :create
  #memberで、users/1/followingが実現できる。https://pikawaka.com/rails/resources#ネストの定義の仕方
  resources :users do
    member do 
      get :following, :followers
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class='text-center' >
<p>2021 ベルリンなう</p>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-white bg-white">
<div class="container">
 <%# ハンバーガーメニュー の内容%>
 <div class="dropdown">
   <button class="btn btn-transparent" type="button" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-bars text-warning fa-3x"></i>
   </button>
   <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to 'トップページへ', root_path, class: "dropdown-item" %>
    <%= link_to 'ユーザー一覧', users_path, class: "dropdown-item" %>
    <%= link_to '作った人のGitHub', 'https://github.com/kazumawada/', class: "dropdown-item", target: :_blank %>
    <%= link_to 'ソースコード', 'https://github.com/kazumawada/myapp', class: "dropdown-item", target: :_blank %>
   </div>
 </div>
 <%# ハンバーガーメニュー %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <%# title %>
  <ul class="navbar-nav mr-auto">　
    <h3><%= link_to 'ベルリンなう', root_path, class: "navbar-brand text-dark" %></h3>
  </ul> 

    <ul class="navbar-nav">
     <%## ログイン後のページ %>

      <% if logged_in? %>
      <%# 　検索機能 %>
        <li class="nav-item">
        <%= form_tag(search_path,:method => 'get') do %>
        <%= text_field_tag :search %>
        <%= submit_tag 'Search', :name => nil %>
        <% end %>
        </li>
    <%# ユーザーアイコン %>
        <li class="nav-item">
         <button type="button" class="btn btn-white p-0">
         <%= link_to current_user, class: "nav-link active text-black" do %>
　　　　　<% if current_user.avatar? %>
         <%= image_tag current_user.avatar.url, class: "rounded-circle", width: "40px", height: "40px" %>
        <% else %>
        <%= image_tag "the-main.jpg", class: "rounded-circle", width: "40px", height: "40px" %>
        <% end %>
        <% end %>
         </button>
        </li>
     <%# ログアウト %>
        <li class="nav-item">
        <button type="button" class="btn btn-light">
         <%= link_to logout_path, class: "nav-link active text-black", title: "logout", method: :delete, data: { confirm: 'ログアウトしますか？'} do %>
        <i class="fas fa-sign-out-alt"></i>
        <% end %>
        </button>
        </li>
     <%# 投稿ボタン %>
       <li class="nav-item">
        <button type="button" class="btn btn-warning"><%= link_to 'Post', new_post_path, class: "nav-link active text-white" %></button>
       </li>
      <% else %>
      <%## ログイン前のページ %>

      <li class="nav-item">
       <%= link_to 'かんたんログイン', testsessions_path, method: :post, class: "btn btn-warning center-block text-white", data: { disable_with: "ログイン中..." } %>
      </li>
      <li class="nav-item">
       <%= link_to 'ログイン', login_path, class: "nav-link active text-dark" %>
      </li>
      <li class="nav-item">
       <%= link_to '新規登録', signup_path, class: "nav-link active text-dark" %>
      </li>

     <% end %>
   </ul>

   </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= yield(:title) %>ベルリンなう</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>
  <body> 
  <div class="container">
  <% unless action_name == "home" %>
  <%= render 'layouts/header' %>
  <% end %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%# debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>